* Wed Jun 21 2017 Cornelius Kölbel <cornelius.koelbel@netknights.it> 0.2
  * Add the app cache which stores the association of user DNs with app markers (#13)
  * Implement a realm mapper which assigns privacyIDEA realms to authentication requests
      based on a strategy, the default being the "static" realm mapper strategy (#13)
  * Add the "app-cache" realm mapper strategy to assign privacyIDEA realms
      based on app markers retrieved from the app cache (#13)
  * Improve error reporting in some corner cases (#17)


* Tue Jun 20 2017 Cornelius Kölbel <cornelius.koelbel@netknights.it> 0.1
  * initial release

